# Introduction to Data Science 2026

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [3]:
import numpy as np
A = np.arange(int(1e7))
B = np.arange(int(1e7))

2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [4]:
def add_with_for(A,B):
    C = np.empty(len(A), dtype=A.dtype)
    for i in range(len(A)):
        C[i] = A[i] + B[i]
    return C

3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [5]:
def add_with_numpy(A,B):
    C = A + B
    return C

### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [6]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
arr1 = np.arange(100).reshape(10,10)

2. Create the following array:

In [8]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [9]:
arr2 = np.zeros((10,10))
arr2[:,1:10:2] = 1

3. Create the following array (D):

In [10]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [11]:
arr3 = np.ones((10,10))
np.fill_diagonal(arr3,0)

4. Create the following array (E):

In [12]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
arr4 = np.fliplr(1-np.eye(10))

5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [14]:
D = arr3
E = arr4
DE = D @ E
det_DE = np.linalg.det(DE)
det_D_times_det_E = np.linalg.det(D) * np.linalg.det(E)
print(det_DE, det_D_times_det_E)

-81.0000000000001 -81.0


-- *Use this markdown cell for your written answer* --

They are the same, and it is not a coincidence! It is a fundamental property of determinants that det(DE) = det(D)*det(E). This holds for any two square matrices.

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [15]:
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()
X = data.data
print(X.shape)

(20640, 8)


2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [16]:
AveBedrms = X[:, 3]
indices = np.where(AveBedrms > 2)[0]
print(indices[:5])
print(len(indices))

[ 710 1023 1024 1030 1102]
235


3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [17]:
HouseAge = X[:, 1]
indices = np.where((0<HouseAge) & (HouseAge<4))[0]
print(len(indices))

124


4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [18]:
Population = X[:, 4]
target = data.target 
mask = target > 0.25
mean_population = np.mean(Population[mask])
print(mean_population)

1425.6833737275813


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [19]:
import json

reviews = []
with open('Automotive_5.json') as file:
    for line in file:
        data = json.loads(line)
        if 'reviewText' in data:
            reviews.append(data['reviewText'])

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [20]:
reviews = [r.lower() for r in reviews]

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [21]:
import string
with open('stopwords-en.txt') as f:
    stopwords = set(f.read().split())
def clean_text(text):
    text = text.translate(str.maketrans('', '', string.punctuation))
    words = text.split()
    words = [word for word in words if word not in stopwords]
    return ' '.join(words) 
reviews = [clean_text(r) for r in reviews]

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [22]:
import sys
import nltk
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
def stem_review(review):
    words = review.split()
    stemmed_words = [stemmer.stem(word) for word in words]
    return ' '.join(stemmed_words)
reviews = [stem_review(r) for r in reviews]

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [23]:
ratings = []
with open('Automotive_5.json') as file:
    for line in file:
        d = json.loads(line)
        if 'reviewText' in d:
            ratings.append(d.get('overall'))

pos_reviews = [r for r, rating in zip(reviews, ratings) if rating in (4, 5)]
neg_reviews = [r for r, rating in zip(reviews, ratings) if rating in (1, 2)]

with open('pos.txt', 'w') as f:
    for r in pos_reviews:
        f.write(r + '\n')

with open('neg.txt', 'w') as f:
    for r in neg_reviews:
        f.write(r + '\n')

## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**

In [24]:
import sqlite3
conn = sqlite3.connect("northwind2000-simplified.sqlite")
cur = conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cur.fetchall())
cur.execute("PRAGMA table_info(Employees);")
print(cur.fetchall())

[('Categories',), ('sqlite_sequence',), ('Customers',), ('Employees',), ('OrderDetails',), ('Orders',), ('Products',), ('Shippers',), ('Suppliers',)]
[(0, 'EmployeeID', 'INTEGER', 0, None, 1), (1, 'LastName', 'TEXT', 0, None, 0), (2, 'FirstName', 'TEXT', 0, None, 0), (3, 'Title', 'TEXT', 0, None, 0), (4, 'TitleOfCourtesy', 'TEXT', 0, None, 0), (5, 'BirthDate', 'DATE', 0, None, 0), (6, 'HireDate', 'DATE', 0, None, 0), (7, 'Address', 'TEXT', 0, None, 0), (8, 'City', 'TEXT', 0, None, 0), (9, 'Region', 'TEXT', 0, None, 0), (10, 'PostalCode', 'TEXT', 0, None, 0), (11, 'Country', 'TEXT', 0, None, 0), (12, 'HomePhone', 'TEXT', 0, None, 0), (13, 'Extension', 'TEXT', 0, None, 0), (14, 'ReportsTo', 'INTEGER', 0, None, 0)]


The above step was done to find out the column names.

In [25]:
#1. Employees hired after 1994-01-01
cur.execute("""
    SELECT FirstName, LastName, HireDate
    FROM Employees
    WHERE HireDate > '1994-01-01'
""")
for row in cur.fetchall():
    print(row)

('Robert', 'King', '1994-01-02')
('Laura', 'Callahan', '1994-03-05')
('Anne', 'Dodsworth', '1994-11-15')


In [26]:
#2. Orders per customer
cur.execute("""
    SELECT CustomerID, COUNT(*) AS order_count
    FROM Orders
    GROUP BY CustomerID
""")
for row in cur.fetchall():
    print(row)

('ALFKI', 6)
('ANATR', 4)
('ANTON', 7)
('AROUT', 13)
('BERGS', 18)
('BLAUS', 7)
('BLONP', 11)
('BOLID', 3)
('BONAP', 17)
('BOTTM', 14)
('BSBEV', 10)
('CACTU', 6)
('CENTC', 1)
('CHOPS', 8)
('COMMI', 5)
('CONSH', 3)
('DRACD', 6)
('DUMON', 4)
('EASTC', 8)
('ERNSH', 30)
('FAMIA', 7)
('FOLIG', 5)
('FOLKO', 19)
('FRANK', 15)
('FRANR', 3)
('FRANS', 6)
('FURIB', 8)
('GALED', 5)
('GODOS', 10)
('GOURL', 9)
('GREAL', 11)
('GROSR', 2)
('HANAR', 14)
('HILAA', 18)
('HUNGC', 5)
('HUNGO', 19)
('ISLAT', 10)
('KOENE', 14)
('LACOR', 4)
('LAMAI', 14)
('LAUGB', 3)
('LAZYK', 2)
('LEHMS', 15)
('LETSS', 4)
('LILAS', 14)
('LINOD', 12)
('LONEP', 8)
('MAGAA', 10)
('MAISD', 7)
('MEREP', 13)
('MORGK', 5)
('NORTS', 3)
('OCEAN', 5)
('OLDWO', 10)
('OTTIK', 10)
('PERIC', 6)
('PICCO', 10)
('PRINI', 5)
('QUEDE', 9)
('QUEEN', 13)
('QUICK', 28)
('RANCH', 5)
('RATTC', 18)
('REGGC', 12)
('RICAR', 11)
('RICSU', 10)
('ROMEY', 5)
('SANTG', 6)
('SAVEA', 31)
('SEVES', 9)
('SIMOB', 7)
('SPECD', 4)
('SPLIR', 9)
('SUPRD', 12)
('THE

In [27]:
#3. Customers who ordered "Chai"
cur.execute("""
    SELECT DISTINCT c.CompanyName
    FROM Customers c
    JOIN Orders o ON c.CustomerID = o.CustomerID
    JOIN OrderDetails od ON o.OrderID = od.OrderID
    JOIN Products p ON od.ProductID = p.ProductID
    WHERE p.ProductName = 'Chai'
""")
for row in cur.fetchall():
    print(row)

('QUICK-Stop',)
('Rattlesnake Canyon Grocery',)
('Lonesome Pine Restaurant',)
('Die Wandernde Kuh',)
('Pericles Comidas clásicas',)
('Chop-suey Chinese',)
('Queen Cozinha',)
("La maison d'Asie",)
('Princesa Isabel Vinhos',)
('Lehmanns Marktstand',)
('Wartian Herkku',)
('Tortuga Restaurante',)
('Mère Paillarde',)
('Du monde entier',)
('Wolski  Zajazd',)
('Blondesddsl père et fils',)
('Hungry Owl All-Night Grocers',)
('Berglunds snabbköp',)
('Save-a-lot Markets',)
('LINO-Delicateses',)
('North/South',)
('HILARION-Abastos',)
('Seven Seas Imports',)
('Wellington Importadora',)
('Godos Cocina Típica',)
('Bottom-Dollar Markets',)
('The Cracker Box',)
('Wilman Kala',)
('Great Lakes Food Market',)
('Suprêmes délices',)
('Eastern Connection',)


In [28]:
#4. Orders placed but not shipped
cur.execute("""
    SELECT *
    FROM Orders
    WHERE ShippedDate IS NULL
""")
for row in cur.fetchall():
    print(row)

(11008, 'ERNSH', 7, '1998-04-08 00:00:00.000', '1998-05-06 00:00:00.000', None, 3, 79.46)
(11019, 'RANCH', 6, '1998-04-13 00:00:00.000', '1998-05-11 00:00:00.000', None, 3, 3.17)
(11039, 'LINOD', 1, '1998-04-21 00:00:00.000', '1998-05-19 00:00:00.000', None, 2, 65)
(11040, 'GREAL', 4, '1998-04-22 00:00:00.000', '1998-05-20 00:00:00.000', None, 3, 18.84)
(11045, 'BOTTM', 6, '1998-04-23 00:00:00.000', '1998-05-21 00:00:00.000', None, 2, 70.58)
(11051, 'LAMAI', 7, '1998-04-27 00:00:00.000', '1998-05-25 00:00:00.000', None, 3, 2.79)
(11054, 'CACTU', 8, '1998-04-28 00:00:00.000', '1998-05-26 00:00:00.000', None, 1, 0.33)
(11058, 'BLAUS', 9, '1998-04-29 00:00:00.000', '1998-05-27 00:00:00.000', None, 3, 31.14)
(11059, 'RICAR', 2, '1998-04-29 00:00:00.000', '1998-06-10 00:00:00.000', None, 2, 85.8)
(11061, 'GREAL', 4, '1998-04-30 00:00:00.000', '1998-06-11 00:00:00.000', None, 3, 14.01)
(11062, 'REGGC', 4, '1998-04-30 00:00:00.000', '1998-05-28 00:00:00.000', None, 2, 29.93)
(11065, 'LILAS', 

In [29]:
#5. Customer with most orders
cur.execute("""
    SELECT CustomerID, COUNT(*) AS order_count
    FROM Orders
    GROUP BY CustomerID
    ORDER BY order_count DESC
    LIMIT 1
""")
print(cur.fetchone())
conn.close()

('SAVEA', 31)
